import {
  LayoutDashboard, User, CreditCard, KanbanSquare, GitFork, ClipboardList, Award, AlertTriangle,
  Users, CalendarClock, GitPullRequest, BarChart3, GraduationCap, FolderKanban, Bug, Library,
  Target, Megaphone, Trophy, Wallet, FileText, LogOut as LogOutIcon, FilePenLine,
  CalendarCheck, MonitorCheck, ShieldCheck, Settings2, ScrollText, FileBarChart, Briefcase, Rocket,
  PlayCircle, Video, UserPlus,
} from "lucide-react";
import { ROLES } from "../utils/constants";

// Each role's sidebar navigation. Screens map 1:1 to FRS modules for that persona.
export const NAV_CONFIG = {
  [ROLES.STUDENT]: [
    { to: "/student/dashboard", label: "Dashboard", icon: LayoutDashboard },
    { to: "/student/subscription", label: "Subscription & Billing", icon: CreditCard },
    { to: "/student/tasks", label: "Sprint Board", icon: KanbanSquare },
    { to: "/student/attendance", label: "Standups & Attendance", icon: CalendarClock },
    { to: "/student/projects", label: "Projects & Challenges", icon: FolderKanban },
    { to: "/student/submissions", label: "GitHub Submissions", icon: GitFork },
    { to: "/student/learning", label: "Video Lessons", icon: PlayCircle },
    { to: "/student/assessments", label: "Assessments", icon: ClipboardList },
    { to: "/student/interviews", label: "My Interviews", icon: Video },
    { to: "/student/pip", label: "PIP & Performance", icon: AlertTriangle },
    { to: "/student/certificates", label: "Certificates", icon: Award },
    { to: "/student/resources", label: "Resource Library", icon: Library },
    { to: "/student/profile", label: "My Profile", icon: User },
    { to: "/student/settings", label: "Account Settings", icon: Settings2 },
  ],
  [ROLES.TRAINER]: [
    { to: "/trainer/dashboard", label: "Dashboard", icon: LayoutDashboard },
    { to: "/trainer/batches", label: "Batches", icon: Users },
    { to: "/trainer/sprints", label: "Sprint Planning", icon: KanbanSquare },
    { to: "/trainer/standups", label: "Standups & Attendance", icon: CalendarClock },
    { to: "/trainer/code-review", label: "Code Review", icon: GitPullRequest },
    { to: "/trainer/assessments", label: "Assessments", icon: Rocket },
    { to: "/trainer/analytics", label: "Performance Analytics", icon: BarChart3 },
    { to: "/trainer/pip", label: "PIP Management", icon: AlertTriangle },
    { to: "/trainer/graduation", label: "Graduation Approval", icon: GraduationCap },
    { to: "/trainer/resources", label: "Resource Library", icon: Library },
    { to: "/trainer/profile", label: "My Profile", icon: User },
    { to: "/trainer/settings", label: "Account Settings", icon: Settings2 },
  ],
  [ROLES.DEVELOPER]: [
    { to: "/developer/dashboard", label: "Dashboard", icon: LayoutDashboard },
    { to: "/developer/client-requirements", label: "Client Requirements", icon: FilePenLine },
    { to: "/developer/project-documents", label: "Client Project Documents", icon: FileText },
    { to: "/developer/projects", label: "Projects", icon: FolderKanban },
    { to: "/developer/bug-challenges", label: "Bug Challenges", icon: Bug },
    { to: "/developer/video-lessons", label: "Video Lessons", icon: PlayCircle },
    { to: "/developer/assessment-bank", label: "Assessment Bank", icon: ClipboardList },
    { to: "/developer/resources", label: "Resource Library", icon: Library },
    { to: "/developer/profile", label: "My Profile", icon: User },
    { to: "/developer/settings", label: "Account Settings", icon: Settings2 },
  ],
  [ROLES.LEAD_GENERATOR]: [
    { to: "/leads/dashboard", label: "Dashboard", icon: LayoutDashboard },
    { to: "/leads/pipeline", label: "Lead Pipeline", icon: Target },
    { to: "/leads/campaigns", label: "Campaigns", icon: Megaphone },
    { to: "/leads/targets", label: "Targets & Leaderboard", icon: Trophy },
    { to: "/leads/profile", label: "My Profile", icon: User },
    { to: "/leads/settings", label: "Account Settings", icon: Settings2 },
  ],
  [ROLES.HR]: [
    { to: "/hr/dashboard", label: "Dashboard", icon: LayoutDashboard },
    { to: "/hr/attendance", label: "Attendance & Leave", icon: CalendarCheck },
    { to: "/hr/payroll", label: "Payroll", icon: Wallet },
    { to: "/hr/documents", label: "Letters & Certifications", icon: FileText },
    { to: "/hr/onboarding", label: "Onboarding", icon: UserPlus },
    { to: "/hr/exit", label: "Exit Management", icon: LogOutIcon },
    { to: "/hr/profile", label: "My Profile", icon: User },
    { to: "/hr/settings", label: "Account Settings", icon: Settings2 },
  ],
  [ROLES.BUSINESS_ANALYST]: [
    { to: "/ba/dashboard", label: "Dashboard", icon: LayoutDashboard },
    { to: "/ba/documents", label: "Requirements Authoring", icon: FilePenLine },
    { to: "/ba/project-documents", label: "Client Project Documents", icon: FileText },
    { to: "/ba/resource-planning", label: "Sprint & Resource Planning", icon: BarChart3 },
    { to: "/ba/client-review", label: "Client Project Review", icon: MonitorCheck },
    { to: "/ba/meetings", label: "Meeting Coordination", icon: CalendarClock },
    { to: "/ba/profile", label: "My Profile", icon: User },
    { to: "/ba/settings", label: "Account Settings", icon: Settings2 },
  ],
  [ROLES.ADMIN]: [
    { to: "/admin/dashboard", label: "Executive Dashboard", icon: LayoutDashboard },
    { to: "/admin/users", label: "User & Role Management", icon: ShieldCheck },
    { to: "/admin/plans", label: "Subscription & Pricing", icon: Settings2 },
    { to: "/admin/transactions", label: "Transactions & Refunds", icon: Wallet },
    { to: "/admin/audit-logs", label: "Audit & Security Logs", icon: ScrollText },
    { to: "/admin/reports", label: "Reporting Engine", icon: FileBarChart },
    { to: "/admin/profile", label: "My Profile", icon: User },
    { to: "/admin/settings", label: "Account Settings", icon: Settings2 },
  ],
  [ROLES.CLIENT]: [
    { to: "/client/dashboard", label: "Dashboard", icon: LayoutDashboard },
    { to: "/client/projects", label: "My Project Requirements", icon: Briefcase },
    { to: "/client/project-documents", label: "Client Project Documents", icon: FileText },
    { to: "/client/talent-pool", label: "Talent Pool", icon: Users },
    { to: "/client/demos", label: "Sprint Demo Reviews", icon: MonitorCheck },
    { to: "/client/profile", label: "My Profile", icon: User },
    { to: "/client/settings", label: "Account Settings", icon: Settings2 },
  ],
};